version: "3.9"

services:  
  webserver:
    build:
      context: ./backend
      dockerfile: DOCKERFILE
    command: python app.py
    ports:
      - 6010:6010
    depends_on:
      - db
    restart: always
    volumes:
      - "./backend:/backend"
    environment:
      SQLALCHEMY_DATABASE_URI: ${SQLALCHEMY_DATABASE_URI}
      SECRET_KEY: ${SECRET_KEY}
      BCRYPT_LOG_ROUNDS: ${BCRYPT_LOG_ROUNDS}
  
  db:
    image: mysql
    restart: always
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: student_life_db
    volumes:             
      - ./backend/init:/docker-entrypoint-initdb.d
    ports:
      - 3310:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: ${PMA_PASSWORD}
    ports:
      - 8083:80

