version: "3.9"

services:
  ###################################
  # Student_School: The Student_School microservice
  ###################################
  student_school:
    build:
      context: ./backend/services/student_school
      dockerfile: student_school.DOCKERFILE
    image: student_school
    restart: always
    environment:
      SQLALCHEMY_DATABASE_URI: mysql+mysqlconnector://root:root@host.docker.internal:3310/student_school
    ports:
      - 6000:6000
  
  ###################################
  # Book: The book microservice
  ###################################
  book:
    build:
      context: ./backend/services/book
      dockerfile: book.DOCKERFILE
    image: book
    restart: always
    environment:
      SQLALCHEMY_DATABASE_URI: mysql+mysqlconnector://root:root@host.docker.internal:3310/book
    ports:
      - 6010:6010
  
  db:
    image: mysql
    restart: always
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    volumes:             
      - ./backend/init:/docker-entrypoint-initdb.d
    ports:
      - 3310:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - 8083:80

